version: '2'

services:
  transmission:
    container_name: bluesky.transmission
    restart: always
    image: linuxserver/transmission:latest
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=Asia/Shanghai
      - USER=transmission #optional
      - PASS=transmission #optional
    ports:
      - "9091:9091"
      - "51413:51413/tcp"
      - "51413:51413/udp"
    volumes:
      - /ext/platform/containers/bluesky.transmission/_data/config:/config
      - /ext/platform/containers/bluesky.transmission/_data/downloads:/downloads
      - /ext/platform/containers/bluesky.transmission/_data/watch:/watch
