#######
### internal index  box 2  port 102xx
version: '2'

services:
 centos-ssh:
  image: "jdeathe/centos-ssh:latest"
  restart: always
  container_name: bluesky.ssh
  hostname: 'ssh.bluesky.lab.home'
  environment:
    - SSH_USER=admin
    - SSH_PASSWORD_AUTHENTICATION=true
    - SSH_USER_PASSWORD=1234qwer
  ports:
    - '10222:22'
  volumes:
    - '/ext/platform/containers/bluesky.ssh/_data/mnt:/mnt'
