#######
### internal index  box 2  port 102xx
version: '2'

services:
 centos-hive:
  image: "jdeathe/centos-ssh:latest"
  restart: always
  container_name: dbox.hive
  hostname: 'hive.dbox.lab.home'
  environment:
    - SSH_USER=admin
    - SSH_PASSWORD_AUTHENTICATION=true
    - SSH_USER_PASSWORD=1234qwer
  ports:
    - '10322:22'
  volumes:
    - '/ext/platform/containers/dbox.hive/_data/mnt:/mnt'
