#######
### 
version: '3'

volumes:
  master_vol:
    external: true
networks:
  master_net:
    external: true


services:
 web:
  image: nginx:latest
  restart: always
  container_name: nginx.dev
  hostname: 'nginx.dev'
  volumes:
    - 'master_vol:/mnt'
    - '/opt/ext/dockervol/macbox/nginx.dev.vol/conf/default.conf:/etc/nginx/conf.d/default.conf'
  networks:
    - master_net

