#######
### Internal Index 3 -   port 103xx
version: '3'

services:
 centos-ssh:
  image: "jdeathe/centos-ssh:latest"
  container_name: devenv.vuehack
  hostname: 'vuehack.devenv.lab.home'
  environment:
    - SSH_USER=admin
    - SSH_PASSWORD_AUTHENTICATION=true
    - SSH_USER_PASSWORD=1234qwer
  ports:
    - '10322:22'
    - '10350-10352:8050-8052'
  volumes:
    - '/ext/platform/containers/devenv.vuehack/_data/mnt:/mnt'
